mm/mmu_notifier: Fix build on !CONFIG_MMU_NOTIFIER
Add missing static inline stub for mmu_notifier_oom_enter() in
the !CONFIG_MMU_NOTIFIER section of include/linux/mmu_notifier.h.

Without this stub, allnoconfig builds fail with:
  mm/oom_kill.c:523: error: implicit declaration of function
  'mmu_notifier_oom_enter'

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202605031109.uxckW5L3-lkp@intel.com/

Signed-off-by: shaikh.kamal <shaikhkamal2012@gmail.com>