alloc_tag: avoid implicit padding in uapi
The impliied padding causes a harmless warning when testing the uapi
headers with -Wpadded that could in theory indicate incompatibilies or
data leaks:

./usr/include/linux/alloc_tag.h:41:1: error: padding struct size to alignment boundary with 7 bytes [-Werror=padded]

The code here is fine, but it's better to make the padding explicit
and avoid the warning here.

Fixes: 1d581ab2348c ("alloc_tag: add ioctl to /proc/allocinfo")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Suren Baghdasaryan <surenb@google.com>